#!/bin/bash

rm *.o
rm *.*~
rm x.*
#rm *.root
rm *.*back
rm ?,*.list
rm TS.list_*
rm *.agevent
rm *.log
rm *-

#rm G4toMode2_EU?
#rm G4toMode2_US?
#rm GEBSort
#rm GEBSort_nogeb
#rm trackMain
rm seg*.spe

rm G4toMode2_???.txt

rm *.gch

rm *.spe
rm *.root
rm *.map

rm x.?
rm y.?
